on:
  push:
    branches:
      - main

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: GRAASP_TEMPLATE_FULL_NAME
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"docs","section":"Documentation","hidden":false},{"type":"test","section":"Tests","hidden":false}]'

      - uses: actions/checkout@v3

      - name: Tag major and minor versions
        uses: jacobsvante/tag-major-minor-action@v0.1
        if: ${{ steps.release.outputs.release_created }}
        with:
          major: ${{ steps.release.outputs.major }}
          minor: ${{ steps.release.outputs.minor }}

      - name: Set tag
        if: ${{ steps.release.outputs.release_created }}
        id: set-tag
        run: |
          REPOSITORY=$(echo '${{ github.repository }}')
          TAG=$(echo '${{ steps.release.outputs.tag_name }}')
          JSON=$(jq -c --null-input --arg repository "$REPOSITORY" --arg tag "$TAG" '{"repository": $repository, "tag": $tag}')
          echo "json=$JSON" >> $GITHUB_OUTPUT

      # Trigger an 'on: repository_dispatch' workflow to run in graasp-deploy repository
      - name: Push tag to Graasp Deploy (Staging)
        if: ${{ steps.release.outputs.release_created }}
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: graasp/graasp-deploy
          event-type: update-staging-version
          client-payload: ${{steps.set-tag.outputs.json}}
